#!/bin/bash
pjstat -A
##pjstat -A | grep "RUN\|$(whoami)"
# allrunnign=$(pjstat -A | grep "RUN")
# user=$(whoami)
# myjobs=$(pjstat | grep -i "$user")
# all="$myjobs\n$allrunnign"
# echo -e "$all"
#grep -i $user <<< "$alljobs"
# echo "$alljobs" | grep RUN | grep -i x | head -n 5